### ISSUE TITLE
Songs stuck in loop: DLNA or Marantz/HEOS app issue?

### ISSUE THREAD

**Issue by make-nz** [jellyfin/jellyfin-plugin-dlna#102]
When I start playing an album songs get stuck in loop.
Song 1 on list will repeat till I press skip, then song 2 will repeat till I press skip…

This is from the reports:
![Image](https://github.com/user-attachments/assets/f53ebc66-4376-4efa-8208-a95275cc8cc3)

This is from a 2 CD Box set with 15 songs per CD

Same with any other CD from my lib

**Comment by make-nz** [comment]
Logs show lots of playback tracker lines on
[Processingplaybacktracker.txt](https://github.com/user-attachments/files/17681690/Processingplaybacktracker.txt)

**Comment by disgustipated** [comment]
Those log lines are from the playback reporting plugin, not dlna plugin. 
Does your player in whatever youre playing with have this icon? ![Image](https://github.com/user-attachments/assets/5ee4c3de-996c-4223-86f9-0ae9393c3451)

I'm not able to reproduce this when i browser to an album and play or when i use play to a dlna device, it will play the whole album

**Comment by make-nz** [comment]
I just send this from the browser, to my Marantz which is in another room, but has speakers in this room.
(Only updated the server a view days ago and never had this before)

![Image](https://github.com/user-attachments/assets/f2a1ce9f-f21d-4674-b83b-70362a219800)

**Comment by disgustipated** [comment]
I'd say try jf server 10.10.1 with v5 of the plugin if you have the capabilities. If you came from JF server 10.8 like i did the move to the dlna plugin made a few things not work as expected. v4 has some things to improve ssdp and v5 has some changes in the relative url that might help with the device youre using. im able to play an album to my lg tv and it will advance to the next track.

**Comment by make-nz** [comment]
Well should hav waited a few days…

> 10.10.1
05 Nov 2024 20:20:39    multimedia/jellyfin: update to 10.10.1

One thing… I went to v3 manualy now, but I do nat have any control over repeat, it's grayed out:
![Image](https://github.com/user-attachments/assets/4652c39c-c892-400d-8963-cf853e692d15)

**Comment by disgustipated** [comment]
That player is part of jf server, looks like they might be doing some changes to that as on 10.10 i dont see any of the controls anymore except the shuffle

**Comment by make-nz** [comment]
Found the issue, but am unsure what to think of it!?
If one uses the HEOS app and sets a _repeat_ on a song, while played via JF DLNA the repeat stays on for days!

Shouldn't DLNA start a new session and reset the repeat?? 
Is this by design?

![Image](https://github.com/user-attachments/assets/c9b2e8ad-b33a-43d3-85b1-aae40ece4afa)

**Comment by make-nz** [comment]
> i dont see any of the controls anymore except the shuffle

You have to use remote control:
![Image](https://github.com/user-attachments/assets/6a32b1cc-5db5-4e53-8156-c85ae3319a2c)

**Comment by disgustipated** [comment]
I think i might have found a similar scenario to this that is reproducible for me to play with. on the android app i set the play to device to be a dlna renderer(in my case macast), i then stop playback by playing tracks on another app. i later noticed that my last.fm scrobbles had the same track scrobbled over and over and over. i had to kill the jf android app to make it stop. i suspect that there is something in the dlna plugin not reporting back to the playing client to stop the playback and the android app is repeatedly doing ...something... making it seem like the track is still playing. 

@make-nz do you happen to have entries like this in your jf server logs as well?
```
[09:21:45] [ERR] [21] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
```
i dont have time at the moment to dig into what i was able to reproduce to see what isnt reporting back to make the app stop acting like its playing but i'll see if i can soon

**Comment by make-nz** [comment]
Sorry for late answer && YES these errors were in my logs, too!

```
[2024-11-08] [ERR] [26] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
```

**Comment by make-nz** [comment]
Also, I still feel very much in the dark, as to knowing what features this plugin has to offer and what not.
@disgustipated could you help there, by any chance?
https://github.com/jellyfin/jellyfin-plugin-dlna/issues/98#issue-2644349503

**Comment by disgustipated** [comment]
im not sure id be the best to answer that extensively, as i only contributed some code that fixed a few things to how devices were discovered and registered after i updated and it stopped working a while back. i do know the plugin scans the network and lists dlna capable devices and makes them available to jellyfin to play to. and then also from those devices you are able to browse the directories in your media library and play directly from the dlna device browser built into that device you are using. thats the general purpose of the plugin and how i use it, there might be more though, theres quite a bit to how it publishes the media library to the receivers and such but i dont think thats what youre looking for as far as "features/offerings". from what ive seen the plugin generally tries to follow the 1.0 dlna spec but portions have been updated to follow the 1.1 dlna spec, im not very well versed in the dlna spec though.

**Comment by make-nz** [comment]
Thanks @disgustipated 
I forgot to add this post: https://github.com/jellyfin/jellyfin-plugin-dlna/issues/48#issuecomment-2289825182
Huge for me is the now playing list, adding songs or albums to the queu… it is just so little this pluging seems to offer

**Comment by disgustipated** [comment]
well the plugin is for sure a small piece in the bigger jellyfin picture, the errors we found in the logs may indicate a problem in JF server, or the android app, I'm not real sure at the moment and im probably not the best to look into it fully as i dont know the JF server code much. i do think we are experiencing the same symptoms though.

**Comment by Shadowghost** [comment]
Fixed on unstable
