### ISSUE TITLE
Play on device does not work

### ISSUE THREAD

**Issue by spacemanspiff2007** [jellyfin/jellyfin-plugin-dlna#107]
Fresh docker install of `10.10.2` - only added an entry to bind to local interface ```192.168.0.13```
During startup this logs:

````
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["192.168.0.13"]
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["192.168.0.13"]
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-11-21 14:59:25.445 +01:00] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[2024-11-21 14:59:40.706 +01:00] [INF] [29] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "DLNA" "5.0.0.0"
````
I notice that the subnet for `192.168.0.0` is wrong, it should be `192.168.0.0/24`.
Nontheless I can select and deselect my TV and it gets discovered
````
[2024-11-21 14:59:46.346 +01:00] [INF] [28] Jellyfin.Plugin.Dlna.Main.DlnaHost: DLNA Session created for "[LG] webOS TV " - "LG TV" using profile "LG Smart TV"
````
However when I click play this happens:
````
[2024-11-21 15:01:28.670 +01:00] [ERR] [62] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/2dbbe260f9cc71d651b382fc128231f0/Playing".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.Dlna.PlayTo.DlnaHttpClient.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.DlnaHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.PlayToController2.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.PlayToController2.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SessionController.Play(String sessionId, PlayCommand playCommand, Guid[] itemIds, Nullable`1 startPositionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 startIndex)
   at lambda_method2207(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
````

**Comment by sl0815** [comment]
Any news on that? I have the same issue with my Sonos speakers. I can select them and connect to them for playback, but when I hit the play button the following error occurs:

```
[ERR] [29] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Sessions/f07c1de5ea381e8bc9e88f3c00248a60/Playing.
```
I run a fresh install of jellyfin in a docker container.

**Comment by disgustipated** [comment]
I'm able to reproduce this now. it only occurs when I have the following 
```all=https://mypublicuri```

in the JF server settings Networking > Published Server URIs. If I remove that i can use play to from browser and cell app

**Comment by spacemanspiff2007** [comment]
As I've written the issue arises even after a fresh install - the field is thus empty for me.

![Image](https://github.com/user-attachments/assets/ca7d841f-4a61-47b7-be16-cc7e81b5f2fe)

**Comment by disgustipated** [comment]
Some further testing, i reproduced the error with debug logging turned on. i found the following immediately before the 500 error
```
[2025-01-14 11:32:03.036 -05:00] [DBG] [36] Jellyfin.Plugin.Dlna.Main.DlnaHost: "goliath" - SetAvTransport Uri: "https://mypublicuri/dlna/videos/47776c75-f6d2-a210-ab95-7017c41a3c34/stream.mkv?DeviceProfileId=a5b06aeabda0e413bd1b80c8b5c24e63&amp;DeviceId=72b18561-491f-884a-1d96-6a687e23dde4&amp;MediaSourceId=47776c75f6d2a210ab957017c41a3c34&amp;Static=true&amp;VideoCodec=h264&amp;AudioCodec=eac3&amp;AudioStreamIndex=1&amp;StartTimeTicks=23840000000&amp;Tag=448db38bcf6ee8f08a61dfa7a1b2235a&amp;dlnaheaders=true" DlnaHeaders: "DLNA.ORG_PN=MATROSKA;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=21D00000000000000000000000000000"
```
i was able to use that url and pull that file down with a browser successfully, i believe something is broken right after that communicating back the action of playing

**Comment by AnAnalogGuy** [comment]
Could this be the same issue?
https://github.com/jellyfin/jellyfin-plugin-dlna/issues/151
