### ISSUE TITLE
Failure to play non-mp3's on default profile (transcoding doesn't kick in?)

### ISSUE THREAD

**Issue by stefaanderoeck** [jellyfin/jellyfin-plugin-dlna#115]
For my Beoplay M5, playing AAC or VORBIS seems to fail consistently, MP3 works correctly. Judging from the logs, it uses the default profile, but playing results in a "500 (Internal Server Error)". (The GUI does not give any feedback at all, positive or negative)
The same setup plays all files correctly to my Marantz, which is a newer device (that probably supports all codecs), and does not fall back to a default profile. 

Expected behaviour: Jellyfin to do the required transcoding for the Beoplay M5?

I've included a sniipet from the debug-enabled logs below. 
Don't hesitate to indicate if and how I obtain more useful debugging information.

Thanks,
Stefaan

```
jellyfin  | [09:46:15] [INF] [43] Jellyfin.Plugin.Dlna.DlnaManager: No matching device profile found. The default will need to be used. 
jellyfin  | {"FriendlyName": "Keuken", "ModelNumber": "2.3.54366.192026550", "SerialNumber": null, "ModelName": "Beoplay M5", "ModelDescription": "", "ModelUrl": "www.bang-olufsen.dk", "Manufacturer": "Bang & Olufsen", "ManufacturerUrl": "www.bang-olufsen.dk", "Headers": [], "$type": "DeviceIdentification"}
jellyfin  | [09:46:15] [DBG] [43] Jellyfin.Plugin.Dlna.Main.DlnaHost: Keuken - Playlist created
jellyfin  | [09:46:15] [DBG] [43] Jellyfin.Plugin.Dlna.Main.DlnaHost: Keuken - Playing 12 items
jellyfin  | [09:46:15] [DBG] [43] Jellyfin.Plugin.Dlna.Main.DlnaHost: Keuken - SetAvTransport Uri: http://192.168.2.43:8096/dlna/audio/24d92aa6-2629-4211-4593-4911a9f9f450/stream.mov?DeviceProfileId=13ef01b2db6343419b831bb7acce3738&amp;DeviceId=bec5a406-f87c-4d29-a936-130a9a921415&amp;MediaSourceId=24d92aa62629421145934911a9f9f450&amp;Static=true&amp;Tag=201f430d8123dadedeea6bb191a10e6d&amp;dlnaheaders=true DlnaHeaders: DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000
jellyfin  | [09:46:15] [DBG] [43] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was not authenticated.
jellyfin  | [09:46:15] [ERR] [48] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Sessions/59221fd468a280888c4779c1622ce041/Playing.
jellyfin  | System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
jellyfin  |    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
jellyfin  |    at Jellyfin.Plugin.Dlna.PlayTo.DlnaHttpClient.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Plugin.Dlna.PlayTo.DlnaHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Plugin.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Plugin.Dlna.PlayTo.PlayToController2.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Plugin.Dlna.PlayTo.PlayToController2.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
jellyfin  |    at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)

```

**Comment by ingoratsdorf** [comment]
I had the same issue with my Yamaha Soundbar YAS-306.
Checked the debug messages, saw that no profile was found and created a profile as per 
[https://github.com/jellyfin/jellyfin-plugin-dlna/issues/119](https://github.com/jellyfin/jellyfin-plugin-dlna/issues/119)

`nano "/var/lib/jellyfin/plugins/configurations/dlna/user/yamaha yas-306.xml"`

with below content, all working now after restart.
Note that I have not checked if it can play anything other than MP3, but since I know it can play MP3, I opted only for that. Might be able to play some others, but could not be bothered to test.


```
<?xml version="1.0"?>
<Profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>yas-306</Name>
  <Identification>
    <FriendlyName>Yamaha YAS-306</FriendlyName>
    <Headers>
      <HttpHeaderInfo name="User-Agent" value="(YAS-306)" match="Substring" />
    </Headers>
  </Identification>
  <Manufacturer>Yamaha</Manufacturer>
  <ManufacturerUrl>https://github.com/jellyfin/jellyfin</ManufacturerUrl>
  <ModelName>Jellyfin Server</ModelName>
  <ModelDescription>UPnP/AV 1.0 Compliant Media Server</ModelDescription>
  <ModelNumber>01</ModelNumber>
  <ModelUrl>https://github.com/jellyfin/jellyfin</ModelUrl>
  <EnableAlbumArtInDidl>false</EnableAlbumArtInDidl>
  <EnableSingleAlbumArtLimit>false</EnableSingleAlbumArtLimit>
  <EnableSingleSubtitleLimit>false</EnableSingleSubtitleLimit>
  <SupportedMediaTypes>Audio</SupportedMediaTypes>
  <AlbumArtPn>JPEG_SM</AlbumArtPn>
  <MaxAlbumArtWidth>480</MaxAlbumArtWidth>
  <MaxAlbumArtHeight>480</MaxAlbumArtHeight>
  <MaxIconWidth>48</MaxIconWidth>
  <MaxIconHeight>48</MaxIconHeight>
  <MaxStreamingBitrate>140000000</MaxStreamingBitrate>
  <MaxStaticBitrate>140000000</MaxStaticBitrate>
  <MusicStreamingTranscodingBitrate>192000</MusicStreamingTranscodingBitrate>
  <MaxStaticMusicBitrate xsi:nil="true" />
  <ProtocolInfo>http-get:*:video/mpeg:*,http-get:*:video/mp4:*,http-get:*:video/vnd.dlna.mpeg-tts:*,http-get:*:video/avi:*,http-get:*:video/x-matroska:*,http-get:*:video/x-ms-wmv:*,http-get:*:video/wtv:*,http-get:*:audio/mpeg:*,http-get:*:audio/mp3:*,http-get:*:audio/mp4:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/wav:*,http-get:*:audio/L16:*,http-get:*:image/jpeg:*,http-get:*:image/png:*,http-get:*:image/gif:*,http-get:*:image/tiff:*</ProtocolInfo>
  <TimelineOffsetSeconds>0</TimelineOffsetSeconds>
  <RequiresPlainVideoItems>false</RequiresPlainVideoItems>
  <RequiresPlainFolders>false</RequiresPlainFolders>
  <EnableMSMediaReceiverRegistrar>false</EnableMSMediaReceiverRegistrar>
  <IgnoreTranscodeByteRangeRequests>false</IgnoreTranscodeByteRangeRequests>
  <XmlRootAttributes />
  <DirectPlayProfiles>
    <DirectPlayProfile container="mp3" audioCodec="mp2,mp3" type="Audio" />
  </DirectPlayProfiles>
  <TranscodingProfiles>
    <TranscodingProfile container="mp3" type="Audio" audioCodec="mp3" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="ts" type="Video" videoCodec="h264" audioCodec="aac" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="jpeg" type="Photo" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
  </TranscodingProfiles>
  <ContainerProfiles />
  <CodecProfiles />
  <ResponseProfiles />
  <SubtitleProfiles />
</Profile>
```
