### ISSUE TITLE
Request to contentdirectory/events results into non XML result

### ISSUE THREAD

**Issue by FelixPetriconi** [jellyfin/jellyfin-plugin-dlna#116]
While finding a reason why it is not possible to get a valid connection to my Panasonic DP-UB820/824 Blu-Ray player, I investigated the communication on protocol level. Here I noticed that the request for contentdirectory/events does not return a valid XML object.
Here is a screenshot of the actual trace result:

![Image](https://github.com/user-attachments/assets/0b5fc917-6121-49d2-8a7c-5ecb7fdbe507)

As you can see that the result is actually a string of the type of the response but not the response. I am happy to do a fix if I would know more about C# and ASP.Net.
With some suggestions I would be happy to proceed here.

**Comment by FelixPetriconi** [comment]
I compared in the meantime the current result with the one that is returned by the original Emby implementation and there the response type is 'text/plain'. So my current assumption is that this [return description](https://github.com/jellyfin/jellyfin-plugin-dlna/blob/master/src/Jellyfin.Plugin.Dlna/Api/DlnaServerController.cs#L221) is not correct. Probably the others non XML return functions too.

**Comment by FelixPetriconi** [comment]
A fix is in this [PR](https://github.com/jellyfin/jellyfin-plugin-dlna/pull/117)

**Comment by zuavra** [comment]
Is this error related by any chance?

```
[18:15:01] [WRN] [35] Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: No output formatter was found for content types '["text/xml", "text/xml"]' to write the response.
[18:15:09] [ERR] [30] Jellyfin.Plugin.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.PersonInfo> MediaBrowser.Controller.Library.ILibraryManager.GetPeople(MediaBrowser.Controller.Entities.InternalPeopleQuery)'.
   at Jellyfin.Plugin.Dlna.Didl.DidlBuilder.AddPeople(BaseItem item, XmlWriter writer)
   at Jellyfin.Plugin.Dlna.Didl.DidlBuilder.AddCommonFields(BaseItem item, Nullable`1 itemStubType, BaseItem context, XmlWriter writer, Filter filter)
   at Jellyfin.Plugin.Dlna.Didl.DidlBuilder.AddGeneralProperties(BaseItem item, Nullable`1 itemStubType, BaseItem context, XmlWriter writer, Filter filter)
   at Jellyfin.Plugin.Dlna.Didl.DidlBuilder.WriteFolderElement(XmlWriter writer, BaseItem folder, Nullable`1 stubType, BaseItem context, Int32 childCount, Filter filter, String requestedId)
   at Jellyfin.Plugin.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
   at Jellyfin.Plugin.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
   at Jellyfin.Plugin.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
   at Jellyfin.Plugin.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
```

The warning appears when Jellyfin is listed as a DLNA server by a mobile (Android) app, and the error appears when the app attempts to browse the DLNA server.

**Comment by rpatterson** [comment]
I think this issue is still happening in v10.0.0.0. For both of my Jellyfin v10.11.0 instances, when trying to browse into the top-level listing/directory for the DLNA/UPnP under both Kodi and VLC, nothing is listed in the client, and the Jellyfin server logs show:

```
[WRN] [37] Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: No output formatter was found for content types '["text/xml", "text/xml"]' to write the response.
```
