### ISSUE TITLE
Can't use DLNA server with Orange TV decoder

### ISSUE THREAD

**Issue by QyuBee** [jellyfin/jellyfin-plugin-dlna#25]
I tried to use Jellyfin as a DLNA server. It works well except with my TV Decoder. I can't read any video from Jellyfin, no matter the video format.

**Logs**

```
[2022-12-29 14:42:27.980 +00:00] [INF] [27] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -fflags +genpts -f matroska,webm  -i file:\"/media/myfile.mkv\" -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 copy -y \"/config/transcodes/a4e7b9904a2636a17cd21a69cea138fe.mkv?deviceprofileid=f97d98ebd94c468b9b07e33463fd50fc&deviceid=test&mediasourceid=5c1b0eefbdecc20924de9249ac65f9c2&static=true&videocodec=h264&audiocodec=dts&audiostreamindex=1&subtitlestreamindex=2&subtitlemethod=embed&tag=04fbab2554e7761c6033dbfbeb790547&dlnaheaders=true\""
[2022-12-29 14:42:28.057 +00:00] [ERR] [17] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[2022-12-29 14:42:28.160 +00:00] [ERR] [17] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/5c1b0eef-bdec-c209-24de-9249ac65f9c2/stream.mkv%3FDeviceProfileId=f97d98ebd94c468b9b07e33463fd50fc&DeviceId=test&MediaSourceId=5c1b0eefbdecc20924de9249ac65f9c2&Static=true&VideoCodec=h264&AudioCodec=dts&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Embed&Tag=04fbab2554e7761c6033dbfbeb790547&dlnaheaders=true".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Helpers.FileStreamResponseHelpers.GetTranscodedFile(StreamState state, Boolean isHeadRequest, HttpContext httpContext, TranscodingJobHelper transcodingJobHelper, String ffmpegCommandLineArguments, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource)
   at Jellyfin.Api.Controllers.VideosController.GetVideoStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method338(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
**FFmpeg Logs**
```
/videos/5c1b0eef-bdec-c209-24de-9249ac65f9c2/stream.mkv%3FDeviceProfileId=f97d98ebd94c468b9b07e33463fd50fc&DeviceId=test&MediaSourceId=5c1b0eefbdecc20924de9249ac65f9c2&Static=true&VideoCodec=h264&AudioCodec=dts&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Embed&Tag=04fbab2554e7761c6033dbfbeb790547&dlnaheaders=true

{"Protocol":0,"Id":"5c1b0eefbdecc20924de9249ac65f9c2","Path":"/media/myfile.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":8213915648,"Name":"my file","IsRemote":false,"ETag":"04fbab2554e7761c6033dbfbeb790547","RunTimeTicks":63129579520,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"h264","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"ChannelLayout":null,"BitRate":10408959,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":808,"Width":1920,"AverageFrameRate":24,"RealFrameRate":24,"Profile":"High","Type":1,"AspectRatio":"2.40:1","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":41,"IsAnamorphic":null},{"Codec":"dts","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"FR","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"FR - Fre - DTS - 5.1 - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":1536000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"DTS","Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"frf","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"FRF","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"Non d\u00E9fini","LocalizedDefault":"Par d\u00E9faut","LocalizedForced":"Forc\u00E9","LocalizedExternal":"External","DisplayTitle":"FRF - Par d\u00E9faut - Forc\u00E9 - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":true,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":11944959,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -fflags +genpts -f matroska,webm  -i file:"/media/myfile.mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 copy -y "/config/transcodes/a4e7b9904a2636a17cd21a69cea138fe.mkv?deviceprofileid=f97d98ebd94c468b9b07e33463fd50fc&deviceid=test&mediasourceid=5c1b0eefbdecc20924de9249ac65f9c2&static=true&videocodec=h264&audiocodec=dts&audiostreamindex=1&subtitlestreamindex=2&subtitlemethod=embed&tag=04fbab2554e7761c6033dbfbeb790547&dlnaheaders=true"


ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from 'file:/media/myfile.mkv':
  Metadata:
    encoder         : libebml v1.0.0 + libmatroska v1.0
  Duration: 01:45:12.96, start: 0.000000, bitrate: 10408 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 674.458000
      Metadata:
        title           : 00:00:00.000
    Chapter #0:1: start 674.458000, end 1110.458000
      Metadata:
        title           : 00:11:14.458
    Chapter #0:2: start 1110.458000, end 1575.792000
      Metadata:
        title           : 00:18:30.458
    Chapter #0:3: start 1575.792000, end 2132.875000
      Metadata:
        title           : 00:26:15.792
    Chapter #0:4: start 2132.875000, end 2694.375000
      Metadata:
        title           : 00:35:32.875
    Chapter #0:5: start 2694.375000, end 3105.667000
      Metadata:
        title           : 00:44:54.375
    Chapter #0:6: start 3105.667000, end 3693.083000
      Metadata:
        title           : 00:51:45.667
    Chapter #0:7: start 3693.083000, end 4188.167000
      Metadata:
        title           : 01:01:33.083
    Chapter #0:8: start 4188.167000, end 4773.000000
      Metadata:
        title           : 01:09:48.167
    Chapter #0:9: start 4773.000000, end 5139.042000
      Metadata:
        title           : 01:19:33.000
    Chapter #0:10: start 5139.042000, end 5883.000000
      Metadata:
        title           : 01:25:39.042
    Chapter #0:11: start 5883.000000, end 6312.958000
      Metadata:
        title           : 01:38:03.000
  Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x808, SAR 1:1 DAR 240:101, 24 fps, 24 tbr, 1k tbn (default)
  Stream #0:1(fre): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Metadata:
      title           : FR
  Stream #0:2(frf): Subtitle: subrip (default) (forced)
    Metadata:
      title           : FRF
[NULL @ 0x558f8e7d7300] Unable to find a suitable output format for '/config/transcodes/a4e7b9904a2636a17cd21a69cea138fe.mkv?deviceprofileid=f97d98ebd94c468b9b07e33463fd50fc&deviceid=test&mediasourceid=5c1b0eefbdecc20924de9249ac65f9c2&static=true&videocodec=h264&audiocodec=dts&audiostreamindex=1&subtitlestreamindex=2&subtitlemethod=embed&tag=04fbab2554e7761c6033dbfbeb790547&dlnaheaders=true'
/config/transcodes/a4e7b9904a2636a17cd21a69cea138fe.mkv?deviceprofileid=f97d98ebd94c468b9b07e33463fd50fc&deviceid=test&mediasourceid=5c1b0eefbdecc20924de9249ac65f9c2&static=true&videocodec=h264&audiocodec=dts&audiostreamindex=1&subtitlestreamindex=2&subtitlemethod=embed&tag=04fbab2554e7761c6033dbfbeb790547&dlnaheaders=true: Invalid argument

```
**Server System (please complete the following information):**
 - OS: Docker container : Debian
 - Jellyfin Version: 10.8.8
 - Reverse proxy: nginx

 
**Client System (please complete the following information):**
 - Device: Orange TV decoder
[Website]( - https://assistance.orange.fr/equipement/tv/decodeur-livebox-play-ihd92-sagem#TvDescription)

**Comment by aubierr** [comment]
Will the solution be integrated?

**Comment by Bbentheclag** [comment]
I'm on jellyfin 10.9.10 and I have the same problem on myOrange UHD tv box.
did the patch will be implemented in a version ?

**Comment by Vebryn** [comment]
So gratefull to integrate this fix !

**Comment by dadodasyra** [comment]
Are you even able to see the server on the list ? When I open the "Réseau" tab nothing shows up even tough I can clearly see it on my windows pc in the network tab on explorer.

**Comment by PandaaAgency** [comment]
Hi ! Still no news about this?

**Comment by dadodasyra** [comment]
Pretty sure it doesnt fix much.
See https://github.com/jellyfin/jellyfin-plugin-dlna/pull/121#issuecomment-2643578090

**Comment by Vebryn** [comment]
Seems fix doesn't work using last plugin version:

```
Nov 04 00:03:46 vega jellyfin[1440796]: [00:03:46] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -fflags +genpts  -i file:"/srv/starr/data/media/tv/C'est pas sorcier/Comment_vivre_100_ans_-_C_est_pas_sorcier_Integrale.mp4" -sn -codec:v:0 copy -fflags +genpts -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libfdk_aac -ab 0 -y "/var/cache/jellyfin/transcodes/aacd7c2721434c6e197b8ebf1356afb8.ts?deviceprofileid=b61b02e7d42d45caaf674f8a4f95029a&deviceid=test&mediasourceid=e24d68ca96c3ceb49b373023d084e044&videocodec=h264&audiocodec=aac&videobitrate=139808000&audiobitrate=192000&requireavc=false&tag=622ff5470b8ac28b38c489f748ca2d4d&transcodereasons=videocodecnotsupported&dlnaheaders=true"
Nov 04 00:03:47 vega jellyfin[1440796]: [00:03:47] [ERR] FFmpeg exited with code 234
Nov 04 00:03:47 vega jellyfin[1440796]: [00:03:47] [ERR] Error processing request. URL GET /dlna/videos/e24d68ca-96c3-ceb4-9b37-3023d084e044/stream.ts%3FDeviceProfileId=b61b02e7d42d45caaf674f8a4f95029a&DeviceId=test&MediaSourceId=e24d68ca96c3ceb49b373023d084e044&VideoCodec=h264&AudioCodec=aac&VideoBitrate=139808000&AudioBitrate=192000&RequireAvc=false&Tag=622ff5470b8ac28b38c489f748ca2d4d&TranscodeReasons=VideoCodecNotSupported&dlnaheaders=true.
Nov 04 00:03:47 vega jellyfin[1440796]: MediaBrowser.Common.FfmpegException: FFmpeg exited with code 234
```

From my understanding, everything after "?" should be removed. Any tip to troubleshooting ?

Best regards

**Comment by QyuBee** [comment]
I finally found the cause of the problem :  
**The device is URL-encoding the `?` character**, and Jellyfin doesn’t accept that.

### Device sends
/dlna/videos/10dc5114-ddee-281a-324e-5d83a8477cc4/stream.mkv`%3F`DeviceProfileId=a229b2458ca543bc9c025252352130ce&DeviceId=test&MediaSourceId=10dc5114ddee281a324e5d83a8477cc4&Static=true&VideoCodec=h264&AudioCodec=ac3&AudioStreamIndex=1&Tag=072716952083bca086e1c83dc767b931&dlnaheaders=true

### Jellyfin accepts

/dlna/videos/10dc5114-ddee-281a-324e-5d83a8477cc4/stream.mkv`?`DeviceProfileId=a229b2458ca543bc9c025252352130ce&DeviceId=test&MediaSourceId=10dc5114ddee281a324e5d83a8477cc4&Static=true&VideoCodec=h264&AudioCodec=ac3&AudioStreamIndex=1&Tag=072716952083bca086e1c83dc767b931&dlnaheaders=true

I am working on a fix

**Comment by QyuBee** [comment]
While investigating, I noticed that the `?` character is encoded as `%3F` by the device.
This results in query parameters being appended to the request path instead of the query string.

Example:

`/Dlna/Videos/{itemId}/stream.mp4%3FdeviceId=xxx&static=true`


From ASP.NET Core’s perspective, this is a malformed URL, so Request.Query is empty and [FromQuery] model binding does not populate any parameters. This breaks DLNA playback for those clients.


Functions concerned :
- https://github.com/jellyfin/jellyfin-plugin-dlna/blob/renovate/major-dotnet-monorepo/src/Jellyfin.Plugin.Dlna.Playback/Api/DlnaVideosController.cs#L140
- https://github.com/jellyfin/jellyfin-plugin-dlna/blob/master/src/Jellyfin.Plugin.Dlna.Playback/Api/DlnaAudioController.cs#L89
- https://github.com/jellyfin/jellyfin-plugin-dlna/blob/master/src/Jellyfin.Plugin.Dlna.Playback/Api/DlnaHlsController.cs#L94
- It might also need to be modified : https://github.com/jellyfin/jellyfin-plugin-dlna/blob/deab450fac5d260703db6e0d2809d2ae8e07658b/src/Jellyfin.Plugin.Dlna.Playback/StreamingHelpers.cs#L467


I am not sure how to fix that.
Should we fix the device code ? I'm not sure they will listen to me.
Should we fix the plugin code ?

**Comment by CyrilP** [comment]
any update? 
I have the same problem

**Comment by franckbrun** [comment]
Hi, 
I've been concerned by the same problem. I managed to solve it by implementing a Middleware via IStartupFilter to intercept and correct malformed URLs (specifically handling %3f as a query separator) before they reach the ASP.NET Core routing engine. I don't know if it's the right solution for this problem and if it worth a PR but it works for me for now.
You can find the fork at https://github.com/franckbrun/jellyfin-plugin-dlna/tree/fix/dlna-url-encoding

**Comment by QyuBee** [comment]
Thank you so much @franckbrun, I was finally able to watch a movie with this device.

**Comment by CyrilP** [comment]
try to do a pull request, maybe it will be integrated here
