### ISSUE TITLE
DLNA Play On remote is broken for Bose Soundtouch 300

### ISSUE THREAD

**Issue by espector** [jellyfin/jellyfin-plugin-dlna#26]
I'm able to play to my Bose Soundtouch 300 sound bar. However, the remote screen is blank and doesn't show the play status. There's no way to control once the music stats casting. I can't pause, go to the next track, etc. 

I can control the volume on Soundtouch though. 

Setup: linuxserver jellyfin docker image, running on Synology. 

Screenshots below. 
![7939729A-577E-49AA-B028-34FEFC70439C](https://user-images.githubusercontent.com/3356907/226623820-0a8f2104-45a0-4d07-9c6c-95d7c012549c.jpeg)
![9830D10A-C002-4169-B7C7-5D930B584F15](https://user-images.githubusercontent.com/3356907/226623823-f45795f7-b3de-43e8-8d6b-475094389d26.png)

**Information from logs:**
Pastebin link with better formatting - https://pastebin.com/igTEJTyB
Log copy below for reference, in case there's an issue with above pastern link.

`[2023-03-24 14:01:23.972 +00:00] [INF] [22] Emby.Dlna.DlnaManager: No matching device profile found. The default will need to be used. 
DeviceIdentification { FriendlyName: "Bedroom", ModelNumber: "", SerialNumber: "38D269A727FF", ModelName: "SoundTouch 10", ModelDescription: "Bose SoundTouch Wireless Streaming Audio Device", ModelUrl: "http://www.bose.com", Manufacturer: "Bose Corporation", ManufacturerUrl: "http://www.bose.com", Headers: [] }
[2023-03-24 14:01:24.363 +00:00] [ERR] [33] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/63fdeabce4dd930090b16412e29fb873/Playing".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.SetNextAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SendNextTrackMessage(Int32 currentPlayListItemIndex, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.PlayToController.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SessionController.Play(String sessionId, PlayCommand playCommand, Guid[] itemIds, Nullable`1 startPositionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 startIndex)
   at lambda_method1036(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-03-24 14:01:24.399 +00:00] [WRN] [33] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://athena.local:8096/Sessions/63fdeabce4dd930090b16412e29fb873/Playing?ItemIds=5ea0e733dd3db589fce68a704353a50b&PlayCommand=PlayNow" to "192.168.1.7" in 0:00:00.7563751 with Status Code 500
[2023-03-24 14:01:24.704 +00:00] [ERR] [20] Emby.Dlna.Main.DlnaEntryPoint: Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2023-03-24 14:01:24.709 +00:00] [ERR] [20] Emby.Dlna.Main.DlnaEntryPoint: Failed to parse xml: 
 "&lt;res duration=&quot;00:08:25.3235200&quot; size=&quot;60821136&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;962886&quot; protocolInfo=&quot;http-get:*:audio/flac:DLNA.ORG_PN=FLAC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.203:8096/audio/efb3d2c1-755c-2353-d390-8cdd119466b6/stream.flac?DeviceProfileId=34cf7511877745b2b91ecbeef97550c4&amp;amp;DeviceId=BO5EBO5E-F00D-F00D-FEED-38D269A727FF&amp;amp;MediaSourceId=efb3d2c1755c2353d3908cdd119466b6&amp;amp;Static=true&amp;amp;Tag=a6846b24fcc47e2fa1b364d1ef16f31e&amp;amp;dlnaheaders=true&lt;/res&gt;"
[2023-03-24 14:01:34.812 +00:00] [ERR] [22] Emby.Dlna.Main.DlnaEntryPoint: Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2023-03-24 14:01:34.814 +00:00] [ERR] [22] Emby.Dlna.Main.DlnaEntryPoint: Failed to parse xml: 
 "&lt;res duration=&quot;00:08:25.3235200&quot; size=&quot;60821136&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;962886&quot; protocolInfo=&quot;http-get:*:audio/flac:DLNA.ORG_PN=FLAC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.203:8096/audio/efb3d2c1-755c-2353-d390-8cdd119466b6/stream.flac?DeviceProfileId=34cf7511877745b2b91ecbeef97550c4&amp;amp;DeviceId=BO5EBO5E-F00D-F00D-FEED-38D269A727FF&amp;amp;MediaSourceId=efb3d2c1755c2353d3908cdd119466b6&amp;amp;Static=true&amp;amp;Tag=a6846b24fcc47e2fa1b364d1ef16f31e&amp;amp;dlnaheaders=true&lt;/res&gt;"
[2023-03-24 14:01:44.871 +00:00] [ERR] [33] Emby.Dlna.Main.DlnaEntryPoint: Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2023-03-24 14:01:44.872 +00:00] [ERR] [33] Emby.Dlna.Main.DlnaEntryPoint: Failed to parse xml: 
 "&lt;res duration=&quot;00:08:25.3235200&quot; size=&quot;60821136&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;962886&quot; protocolInfo=&quot;http-get:*:audio/flac:DLNA.ORG_PN=FLAC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.203:8096/audio/efb3d2c1-755c-2353-d390-8cdd119466b6/stream.flac?DeviceProfileId=34cf7511877745b2b91ecbeef97550c4&amp;amp;DeviceId=BO5EBO5E-F00D-F00D-FEED-38D269A727FF&amp;amp;MediaSourceId=efb3d2c1755c2353d3908cdd119466b6&amp;amp;Static=true&amp;amp;Tag=a6846b24fcc47e2fa1b364d1ef16f31e&amp;amp;dlnaheaders=true&lt;/res&gt;"
[2023-03-24 14:01:54.950 +00:00] [ERR] [51] Emby.Dlna.Main.DlnaEntryPoint: Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2023-03-24 14:01:54.956 +00:00] [ERR] [51] Emby.Dlna.Main.DlnaEntryPoint: Failed to parse xml: 
 "&lt;res duration=&quot;00:08:25.3235200&quot; size=&quot;60821136&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;962886&quot; protocolInfo=&quot;http-get:*:audio/flac:DLNA.ORG_PN=FLAC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.203:8096/audio/efb3d2c1-755c-2353-d390-8cdd119466b6/stream.flac?DeviceProfileId=34cf7511877745b2b91ecbeef97550c4&amp;amp;DeviceId=BO5EBO5E-F00D-F00D-FEED-38D269A727FF&amp;amp;MediaSourceId=efb3d2c1755c2353d3908cdd119466b6&amp;amp;Static=true&amp;amp;Tag=a6846b24fcc47e2fa1b364d1ef16f31e&amp;amp;dlnaheaders=true&lt;/res&gt;"

AC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.203:8096/audio/efb3d2c1-755c-2353-d390-8cdd119466b6/stream.flac?DeviceProfileId=34cf7511877745b2b91ecbeef97550c4&amp;amp;DeviceId=BO5EBO5E-F00D-F00D-FEED-38D269A727FF&amp;amp;MediaSourceId=efb3d2c1755c2353d3908cdd119466b6&amp;amp;Static=true&amp;amp;Tag=a6846b24fcc47e2fa1b364d1ef16f31e&amp;amp;dlnaheaders=true&lt;/res&gt;"
[2023-03-24 14:02:25.137 +00:00] [ERR] [51] Emby.Dlna.Main.DlnaEntryPoint: Uncaught exception while parsing xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Emby.Dlna.PlayTo.Device.ParseResponse(String xml)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
[2023-03-24 14:02:25.140 +00:00] [ERR] [51] Emby.Dlna.Main.DlnaEntryPoint: Failed to parse xml: 
 "&lt;res duration=&quot;00:08:25.3235200&quot; size=&quot;60821136&quot; nrAudioChannels=&quot;2&quot; sampleFrequency=&quot;44100&quot; bitrate=&quot;962886&quot; protocolInfo=&quot;http-get:*:audio/flac:DLNA.ORG_PN=FLAC;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01D00000000000000000000000000000&quot;&gt;http://192.168.1.203:8096/audio/efb3d2c1-755c-2353-d390-8cdd119466b6/stream.flac?DeviceProfileId=34cf7511877745b2b91ecbeef97550c4&amp;amp;DeviceId=BO5EBO5E-F00D-F00D-FEED-38D269A727FF&amp;amp;MediaSourceId=efb3d2c1755c2353d3908cdd119466b6&amp;amp;Static=true&amp;amp;Tag=a6846b24fcc47e2fa1b364d1ef16f31e&amp;amp;dlnaheaders=true&lt;/res&gt;"
`

**Comment by MoriarT3a** [comment]
It also doesn't work for my bose soundbar 500. @espector do you have found a fix?
