### ISSUE TITLE
DLNA Error Updating device info

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-plugin-dlna#34]
**Describe the bug**
An error is shown in the console when about updating the device info. I'm not sure if this causes it not to show the playing media in the dashboard.

**System (please complete the following information):**
 - OS: macOS
 - Virtualization: None
 - Clients: DLNA
 - Browser: N/A
 - Jellyfin Version: 10.7-RC2
 - Playback: DirectPlay
 - Installed Plugins: Kodi Sync Queue and Playback Reporting
 - Reverse Proxy: Nginx
 - Base URL: None
 - Networking: Host
 - Storage: NFS

**To Reproduce**

1. Cast to DLNA Device
2. Play something
3. See error

**Expected behavior**

No error should appear.

**Logs**

```
18:07:52] [ERR] [118] Emby.Dlna.Main.DlnaEntryPoint: Error updating device info for User_s Bedroom                                                                                                                                       
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 1, position 2300.                                                                                                                                      
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)                                                                                                                                                                                       
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)                                                                                                                                                                         
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)                                                                                                                                       
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(XContainer rootContainer, XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.SsdpHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.GetPositionInfo(TransportCommands avCommands, CancellationToken cancellationToken)
   at Emby.Dlna.PlayTo.Device.TimerCallback(Object sender)
```

**Additional context**
The device is called User's Bedroom but is showing up as User_s Bedroom. Not sure if that affects anything. Also I'm pretty sure 10.6 is also affected by this.

**Comment by jasonm23** [comment]
If I replace the plugin manifest url with:

    https://sgp1.mirror.jellyfin.org/releases/plugin/manifest-stable.json

It works fine.

**Comment by Shadowghost** [comment]
Fixed by the above mentioned PR
