### ISSUE TITLE
Playstation: can't play any movies or tv shows

### ISSUE THREAD

**Issue by jscancella** [jellyfin/jellyfin-plugin-dlna#42]
I am unable to play videos on my PS3. When playing using Universal Media Server the same files play file. Both are using DLNA so I don't believe it is something with the files.

**Media Info of the file**
Movie example:
```
310 To Yuma
Containermov
PathC:\media\movies\310 To Yuma\310 To Yuma.m4v
Size2451 MB
Video
Title720p H264
CodecH264
Codec tagavc1
AVCNo
ProfileMain
Level31
Resolution1280x720
Aspect ratio2.40:1
InterlacedNo
Framerate23.976025
Bitrate2629 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL0
Audio
TitleEng AAC stereo Default
Languageeng
CodecAAC
Codec tagmp4a
ProfileLC
Layoutstereo
Channels2 ch
Bitrate160 kbps
Sample rate48000 Hz
DefaultYes
```

TV show example:
```
01 pilot
Containermov
PathC:\media\tv shows\The Big Bang Theory\Season 1\01 pilot.m4v
Size283 MB
Video
Title480p H264
CodecH264
Codec tagavc1
AVCNo
ProfileMain
Level31
Resolution720x480
Aspect ratio16:9
InterlacedNo
Framerate23.978342
Bitrate1560 kbps
Bit depth8 bit
Pixel formatyuv420p
Ref frames1
NAL0
Audio
TitleEng AAC stereo Default
Languageeng
CodecAAC
Codec tagmp4a
ProfileLC
Layoutstereo
Channels2 ch
Bitrate160 kbps
Sample rate48000 Hz
DefaultYes
```

**Logs**
```
[2020-08-09 22:46:12.324 -04:00] [ERR] [67] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "A task was canceled". URL: "http://localhost:5001/favicon.ico"
[2020-08-09 22:46:53.915 -04:00] [INF] [67] Emby.Server.Implementations.IO.LibraryMonitor: "Harry Potter and the Deathly Hallows: Part 2" ("C:\media\movies\Harry Potter\8 - Harry Potter And The Deathly Hallows Part 2\Harry Potter And The Deathly Hallows Part 2.m4v") will be refreshed.
[2020-08-09 22:46:54.075 -04:00] [ERR] [15] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2020-08-09 22:47:54.038 -04:00] [INF] [59] Emby.Server.Implementations.IO.LibraryMonitor: "Harry Potter and the Deathly Hallows: Part 2" ("C:\media\movies\Harry Potter\8 - Harry Potter And The Deathly Hallows Part 2\Harry Potter And The Deathly Hallows Part 2.m4v") will be refreshed.
[2020-08-09 22:47:54.200 -04:00] [ERR] [60] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2020-08-09 22:48:54.050 -04:00] [INF] [49] Emby.Server.Implementations.IO.LibraryMonitor: "Harry Potter and the Deathly Hallows: Part 2" ("C:\media\movies\Harry Potter\8 - Harry Potter And The Deathly Hallows Part 2\Harry Potter And The Deathly Hallows Part 2.m4v") will be refreshed.
[2020-08-09 22:48:54.210 -04:00] [ERR] [41] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2020-08-09 22:49:25.687 -04:00] [INF] [22] Emby.Server.Implementations.IO.LibraryMonitor: "2 - The Lord Of The Rings - The Two Towers" ("C:\media\movies\The Lord of the Rings\2 - The Lord Of The Rings - The Two Towers") will be refreshed.
[2020-08-09 22:49:25.905 -04:00] [INF] [41] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshStart "6fecf0d7e2a2d6c3bed6e0e9d0ce7872"
[2020-08-09 22:49:25.919 -04:00] [INF] [41] MediaBrowser.Providers.Manager.ProviderManager: OnRefreshComplete "6fecf0d7e2a2d6c3bed6e0e9d0ce7872"
[2020-08-09 22:49:54.054 -04:00] [INF] [72] Emby.Server.Implementations.IO.LibraryMonitor: "Harry Potter and the Deathly Hallows: Part 2" ("C:\media\movies\Harry Potter\8 - Harry Potter And The Deathly Hallows Part 2\Harry Potter And The Deathly Hallows Part 2.m4v") will be refreshed.
[2020-08-09 22:49:54.212 -04:00] [ERR] [71] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.Exception: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2020-08-09 22:50:30.993 -04:00] [INF] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe". pathType: "Custom"
[2020-08-09 22:50:31.059 -04:00] [INF] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "unknown"
[2020-08-09 22:50:31.060 -04:00] [WRN] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: Failed version check: "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe"
[2020-08-09 22:50:31.144 -04:00] [INF] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[2020-08-09 22:50:31.219 -04:00] [INF] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-08-09 22:50:31.277 -04:00] [INF] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va"]
[2020-08-09 22:50:31.279 -04:00] [INF] [46] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe"
[2020-08-09 22:50:39.060 -04:00] [INF] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe". pathType: "Custom"
[2020-08-09 22:50:39.116 -04:00] [INF] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "unknown"
[2020-08-09 22:50:39.117 -04:00] [WRN] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: Failed version check: "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe"
[2020-08-09 22:50:39.191 -04:00] [INF] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "mp3"]
[2020-08-09 22:50:39.266 -04:00] [INF] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "libmp3lame", "libopus", "libvorbis", "srt"]
[2020-08-09 22:50:39.323 -04:00] [INF] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "dxva2", "qsv", "d3d11va"]
[2020-08-09 22:50:39.325 -04:00] [INF] [74] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Custom: "C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe"
[2020-08-09 22:50:54.069 -04:00] [INF] [73] Emby.Server.Implementations.IO.LibraryMonitor: "Harry Potter and the Deathly Hallows: Part 2" ("C:\media\movies\Harry Potter\8 - Harry Potter And The Deathly Hallows Part 2\Harry Potter And The Deathly Hallows Part 2.m4v") will be refreshed.
[2020-08-09 22:50:54.182 -04:00] [ERR] [73] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2020-08-09 22:51:34.530 -04:00] [ERR] [61] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:34.531 -04:00] [WRN] [61] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to "192.168.1.210". Time (slow): 0:00:00.5571249. "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:35.884 -04:00] [ERR] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:35.886 -04:00] [WRN] [30] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to "192.168.1.210". Time (slow): 0:00:01.3265326. "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:36.437 -04:00] [ERR] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:36.438 -04:00] [WRN] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to "192.168.1.210". Time (slow): 0:00:00.5246909. "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:36.968 -04:00] [ERR] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". URL: "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:36.969 -04:00] [WRN] [58] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 206 to "192.168.1.210". Time (slow): 0:00:00.5108355. "http://192.168.1.187:5001/videos/4458d53e-3430-e704-85ab-93cbc88a199f/stream.mp4?DeviceProfileId=2d7ca7c201d8ddad7ebceb783b8a0416&DeviceId=test&MediaSourceId=4458d53e3430e70485ab93cbc88a199f&Static=true&AudioStreamIndex=1&Tag=f208f4b9bbacf454d613a5cf2b052107&dlnaheaders=true"
[2020-08-09 22:51:37.283 -04:00] [ERR] [58] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HM1SQRNLT0OH"", Request id ""0HM1SQRNLT0OH:00000001"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (765828 of 765952).
[2020-08-09 22:51:41.343 -04:00] [ERR] [58] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HM1SQRNLT0OI"", Request id ""0HM1SQRNLT0OI:00000001"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too few bytes written (0 of 124).
[2020-08-09 22:51:54.076 -04:00] [INF] [63] Emby.Server.Implementations.IO.LibraryMonitor: "Harry Potter and the Deathly Hallows: Part 2" ("C:\media\movies\Harry Potter\8 - Harry Potter And The Deathly Hallows Part 2\Harry Potter And The Deathly Hallows Part 2.m4v") will be refreshed.
[2020-08-09 22:51:54.189 -04:00] [ERR] [28] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**FFmpeg Logs**

not sure where these are located, but if you tell me where to look I can get them

**Stats for Nerds Screenshots**

Sorry, I have no idea what this is

**Server System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.6.2
 - Hardware settings & device: GTX1080 Ryzen 5 3600
 - Reverse proxy: no
 - Other hardware notes: 
 
**Client System (please complete the following information):**
 - Device: PS3
 - OS: PS3?
 - Client: DLNA
 - Browser (if Web client): N/A
 - Client and Browser Version: Not sure?

**Comment by lucastucious** [comment]
My ps4 doesnt see the Jellyfin DLNA

**Comment by saeziae** [comment]
Still issue on 2025. PS3 says "The data type is not supported". There is `Sony PlayStation 3.xml` under default installation but apparently is not working.
