### ISSUE TITLE
DLNA implementation doesn't work with Bigscreen app

### ISSUE THREAD

**Issue by Nullcaller** [jellyfin/jellyfin-plugin-dlna#81]
The plugin doesn't currently work with Bigscreen app on Quest 2.

Presently, there are issues with discovery, as mentioned in #64. But it appears they'll be fixed soon.

But even if the Jellyfin DLNA server is discovered, trying to access it yields no results, with the Bigscreen app erroring out: "path couldn't be accessed".

As to why it can't be accessed... I took a packet capture of what the Bigscreen app attempts to do, and it's fun.

Bigscreen attemtps to discover DLNA servers, by sending an SSDP packet (UDP, Destination Address 239.255.255.250, Destination Port 1900, Source Port 45117):

```
M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 15
ST: ssdp:all
```

Jellyfin then replies to it with 21 packets (UDP, Source Port 56692, Destination Port 45117), all having largely the same content along the lines of

```
HTTP/1.1 200 OK
EXT: 
DATE: Tue, 22 Oct 2024 16:35:04 GMT
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age = 1800
ST: upnp:rootdevice
SERVER: Unix/5.15.0.124 UPnP/1.0 RSSDP/1.0
USN: uuid:49729ae3-b342-4267-a1ca-c8ff06010523::upnp:rootdevice
LOCATION: http://10.x.x.x:8096/dlna/49729ae3-b342-4267-a1ca-c8ff06010523/description.xml
```

At this point, the Bigscreen app is still seemingly acting sane. It switches to TCP, and using source port 57814 and destination port 8096, it asks of the server (at this point, the IP of the Quest 2 also switches to the IP of the gateway, i.e. 10.0.0.1, but this I suppose is of no significance):

```
GET /dlna/49729ae3-b342-4267-a1ca-c8ff06010523/description.xml HTTP/1.1
User-Agent: Bigscreen/0.933.55.9e0c57-beta-cloud-browser-beta
Connection: keep-alive
Host: 10.x.x.x:8096
```

To which it receives a seemingly perfectly satisfactory reply:

```

HTTP/1.1 200 OK
Content-Type: text/xml; charset=utf-8
Date: Tue, 22 Oct 2024 16:35:03 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-Response-Time-ms: 39.0161

c67
%XML%
0
```

where `%XML%` denotes the contents of [description.xml.txt](https://github.com/user-attachments/files/17480127/description.xml.txt).

The Bigscreen app reads all of that, and decides to go for the `ContentDirectory` service. Here's what it sends to Jellyfin (TCP, same ports):

```
GET /ttp://10.x.x.x:8096/dlna/49729ae3-b342-4267-a1ca-c8ff06010523/contentdirectory/contentdirectory.xml HTTP/1.1
User-Agent: Bigscreen/0.933.55.9e0c57-beta-cloud-browser-beta
Host: 10.x.x.x:8096
```

I think you get it by now...

Of course, Bigscreen receives its 404 Not Found, as it should. Then it goes for `ConnectionManager` service, receives the same reply, and then it dies, erroring out in "path couldn't be accessed". Which path? Well, that would probably be `/ttp://10.x.x.x:8096/dlna/49729ae3-b342-4267-a1ca-c8ff06010523/contentdirectory/contentdirectory.xml`.

As you can probably guess, if we capture the conversation between Bigscreen and Plex, we will see that Plex, in its `DeviceDescription.xml` (which serves the same purpose as Jellyfin's `description.xml`), uses relative paths: [DeviceDescription.xml.txt](https://github.com/user-attachments/files/17480293/DeviceDescription.xml.txt)

So it seems like what Bigscreen is doing, is expecting a relative path, and if the path just so happens not to be relative, it does the most obvious and logical thing and replaces the first symbol of the path with a slash to make it relative. Fun.

**Comment by Nullcaller** [comment]
I previously stated that I took packet captures about 2 years ago and blamed the error on differences between Jellyfin's and Plex's direcotry structure. I misremembered. I only explored the directory structures with VLC. I _was_ going to then take packet captures, but I never actually got around to it. That's why I remembered it like I did.

**Comment by Nullcaller** [comment]
I tried modifying `src/Jellyfin.Plugin.Dlna/Server/DescriptionXmlBuilder.cs`, specifically the line

```
url = _serverAddress.TrimEnd('/') + "/dlna/" + _serverUdn + "/" + url.TrimStart('/');
```

in the `BuildUrl` method. As modified, it reads:

```
url = "/dlna/" + _serverUdn + "/" + url.TrimStart('/');
```

Now, at the very least, Bigscreen can get to the actual top-level directories. It doesn't get much further than that, though. Entering any of the 'Movies', 'Shows' or 'Music' directories will make the spinny thing spin indefinitely.

I took a packet capture and am in process of trying to make sense of it.

**Comment by Nullcaller** [comment]
Seems like Bigscreen can't wrap its head around non-GUID id arguments in DIDL.

For example, as a response to the POST query Bigscreen makes to get the items at the root of the DLNA server, you might get an item such as

```
<container restricted="1" searchable="1" childCount="0" id="04f09db219b5cb5758cd88c3c7db037c" parentID="e9d5075a555c1cbc394eec4cef295274">
	<dc:title>Movies</dc:title>
	<upnp:class>object.container.storageFolder</upnp:class>
	<upnp:albumArtURI dlna:profileID="JPEG_SM">http://10.x.x.x:8096/Items/04f09db219b5cb5758cd88c3c7db037c/Images/Primary/0/222790bc3dd3d80c754283c770fe24e6/jpg/480/480/0/0</upnp:albumArtURI>
	<upnp:icon>http://10.x.x.x:8096/Items/04f09db219b5cb5758cd88c3c7db037c/Images/Primary/0/222790bc3dd3d80c754283c770fe24e6/jpg/48/48/0/0</upnp:icon>
	<res ...>...</res>
</container>
```

If you now browse into this item, you will get items like

```
<container restricted="1" searchable="1" childCount="0" id="latest_04f09db219b5cb5758cd88c3c7db037c" parentID="04f09db219b5cb5758cd88c3c7db037c">
	<dc:title>Latest</dc:title>
	<upnp:class>object.container.storageFolder</upnp:class>
	<upnp:albumArtURI dlna:profileID="JPEG_SM">http://10.x.x.x:8096/Items/04f09db219b5cb5758cd88c3c7db037c/Images/Primary/0/222790bc3dd3d80c754283c770fe24e6/jpg/480/480/0/0</upnp:albumArtURI>
	<upnp:icon>http://10.x.x.x:8096/Items/04f09db219b5cb5758cd88c3c7db037c/Images/Primary/0/222790bc3dd3d80c754283c770fe24e6/jpg/48/48/0/0</upnp:icon>
	<res ...>...</res>
</container>
```

And the id of that item, is "latest_04f09db219b5cb5758cd88c3c7db037c". This unconventional ID is seemingly the only thing that's different about the items that don't load from the items that do. At least, I can't find anything else, really.

And once Bigscreen does encounter an ID like this, it does actually get stuck in an infinite loop, repeating its queries and incrementing the `StartingIndex` in them by a factor of 10000. It went up to at least 460000, before I got bored of clicking through packets.

**Comment by Nullcaller** [comment]
Yeah, no. It's not IDs. In fact, it's not anything else in DIDL, either. I've made DIDL look exactly like Plex's, and it doesn't appear to do anything.

**Comment by Nullcaller** [comment]
I think I figured it out. It seems that Bigscreen attempts to list all elements in a folder by requesting 10000 elements, then incrementing the `SatrtingIndex` by 10000 and seeing whether any elements remain, i.e. whether or not `NumberReturned` goes to zero.

The DLNA plugin somehow correctly returns zero elements when Bigscreen tries to access the root directory. However, when Bigscreen tries to access any of the folders inside the root directory, the DLNA plugin shortcircuits and returns items starting from zero (I presume up to 10000). Since the number of returned items never goes to zero, Bigscreen never stops looking for items.

**Comment by Nullcaller** [comment]
No, couldn't let go of it. I was right.

In `src/Jellyfin.Plugin.Dlna/ContentDirectory/ControlHandler.cs`, there are methods for building the response to the Browse query. Specifically, `GetMusicFolders`, `GetMovieFolders` and `GetTvFolders`. There may be more, but these interest me most.

These build both the data that goes into the 'stubs', i.e. the actual track/movie/show items, and the data that goes into the folders in the root directory, i.e. 'Continue watching', 'Latest', etc.

Let's focus on `GetMovieFolders`. If a stub is requested, it makes a request to Jellyfin in order to actually build the movie folders, by calling `GetMovieContinueWatching`, `GetLatest`, etc. And then Jellyfin handles the query. But what happens if it builds the root movie folder itself? Well, it builds an array of six items, then it checks whether these six items fit under the limit of requested item amount, then it just more or less returns the whole array. Regardless of the start index.

I added a quick-and-dirty check for whether or not `startIndex` is larger than array length, because I couldn't be bothered to do it properly. After the limit check, I added:

```
if (startIndex >= array.Length)
{
    array = new ServerItem[] { };
    return new QueryResult<ServerItem>(
        startIndex,
        array.Length,
        array);
}
```

And now it works. Huzzah! Excelsior!

**Comment by Nullcaller** [comment]
Here's the quick-and-dirty build for anyone interested: [Jellyfin.Plugin.Dlna.zip](https://github.com/user-attachments/files/17483536/Jellyfin.Plugin.Dlna.zip)

Replace the `Jellyfin.Plugin.Dlna.dll` in the plugin folder (v3 plugin required) with the one from the archive. I don't guarantee that it will work perfectly. In fact, for all I know, it might blow your PC/server up. But I do guarantee that, if you can get Bigscreen to find a Jellyfin server running this dll, _it is going to work._ I mean, at least in some capacity, codec compatibility aside, you know.

**Comment by Nullcaller** [comment]
And also, it's just fun how the Bigscreen-related corner of the Internet propagated this myth that "Jellyfin's DLNA implementation is non-standard", and therefore it will forever be unsupported by Bigscreen. Well. **Non-standard my ass.**

**Comment by disgustipated** [comment]
I dropped this in place and will test it a bit with regular usage from my lg tv to see if there is any impact outside of the bigscreen app. I havent tried the vr app just yet.

**Comment by Nullcaller** [comment]
I'll start a PR later this day. Also note that as it is, it breaks base path functionality. I wanted to fix it now, but couldn't get the server to show up in Bigscreen with that change, and I don't have enough time right now to analyze whether it's due to Bigscreen being dumb or me having fat fingers.

**Comment by Nullcaller** [comment]
Weird. I'm gonna test it on mobile VLC, BubbleUPnP and on maybe on a Samsung TV, probably in about 5-6 hours, and report on my findings.

If they're having trouble with relative paths, I'll introduce a User-Agent check so that only Bigscreen receives relative paths in description.xml. Now that I think of it, maybe it would be best to do so anyway...

**Comment by disgustipated** [comment]
From what I was reading in the upnp spec, the usage of relative paths are defined in upnp 1.1, which makes some sense with the description.xml you had for Plex. the major and minor version at the top indicated they were using 1.1 while we are still advertising 1.0 in the description.xml

**Comment by Nullcaller** [comment]
My results:

* VLC works (v3.5.7 from FDroid, Android 14)
* BubbleUPnP works (v4.4.5 from Play Store, Android 14)
* TV ain't seeing the server, but that's probably because of my network configuration

I'm happy to change it so that relative paths are only presented to Bigscreen, though. I already wrote the code on my way home, and it makes me less nervous that I'm gonna break people's setups. I mean, you know how it goes. Somebody probably has an Arduino that is single-handedly preventing a nuclear war from starting, but entirely depends on the Jellyfin DLNA plugin serving absolute paths in `description.xml` ([relevant xkcd](https://xkcd.com/1172/))

**Comment by Nullcaller** [comment]
I committed the user-agent detector into the branch of #83, as well as a bodge that makes the 'Latest' stub folder work

**Comment by Nullcaller** [comment]
I made combined DLLs with both SSDP changes and bigscreen compat, they can be found [here](https://github.com/Nullcaller/jellyfin-plugin-dlna/releases/tag/temp-ssdp-bs-combined). They're kinda buggy in JF UI though, DLLs have a version of 0.0.0.0 and disabling the plugin doesn't seem to work.

**Comment by Nullcaller** [comment]
4.0.0.0 with bigscreen compat can be found [on GitHub actions of my fork](https://github.com/Nullcaller/jellyfin-plugin-dlna/actions/runs/11544370672) or as a zip file: .
[build-artifact.zip](https://github.com/user-attachments/files/17535652/build-artifact.zip)

**Comment by disgustipated** [comment]
This seems to be working well with my tv, and vlc desktop. I did test in my index (which i hadnt picked up in a while and noticed i unfortunately left it somewhere that light has now burned small spots on the lcds) and tried using bigscreen beta and it was able to list and play videos. 

im not sure yet where this is coming from but i noticed some errors that i think might be from 10.10 changes about authoization. things seem to continue to work though. going to go back to the release v4 to see if this is still being posted
```
[2024-10-27 08:41:59.028 -04:00] [ERR] [11] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Sessions/426533c9fc6d30842eb3000c4921403b/Playing".
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.Dlna.PlayTo.DlnaHttpClient.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.DlnaHttpClient.SendCommandAsync(String baseUrl, DeviceService service, String command, String postData, String header, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.Device.SetAvTransport(String url, String header, String metaData, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.PlayToController2.SetPlaylistIndex(Int32 index, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Dlna.PlayTo.PlayToController2.PlayItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendMessageToSession[T](SessionInfo session, SessionMessageType name, T data, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Session.SessionManager.SendPlayCommand(String controllingSessionId, String sessionId, PlayRequest command, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.SessionController.Play(String sessionId, PlayCommand playCommand, Guid[] itemIds, Nullable`1 startPositionTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 startIndex)
   at lambda_method740(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by Nullcaller** [comment]
First of all, so sorry to hear about your index... I'm glad everything else works okay, though.

As for the error, I tried quickly looking into what all of those classes do, and failed at that spectacularly, so I'm gonna have to take a proper go at a later date. Since I haven't touched anything to do with playback, I'm fairly certain I'm not to blame for this. But still, it's a bit discombobulating.

**Comment by disgustipated** [comment]
i went back to releasev4, and now back to your built item and havent seen it again with either. possibly it was something cached on a device somewhere. will keep an eye out, looking good so far though.

**Comment by Elyviere** [comment]
> 4.0.0.0 with bigscreen compat can be found [on GitHub actions of my fork](https://github.com/Nullcaller/jellyfin-plugin-dlna/actions/runs/11544370672) or as a zip file: [build-artifact.zip](https://github.com/user-attachments/files/17535652/build-artifact.zip).

How long until an official release do you think? If it'll be coming soon I'll just wait for it.

**Comment by Nullcaller** [comment]
I've pretty much no real idea. Judging by the fact that I missed the v4 release... I don't know. May be a month, may be two months, may be six. That's assuming the release cadence remains the same. I mean, there's also the [admittedly quite slim] chance that, since Quest 3s recently started shipping and Quest 3 got a price decrease, Jellyfin devs will be more inclined to get this out the door more quickly. I wouldn't be _counting_ on it, but one can always hope.

**Comment by Nullcaller** [comment]
Also, the automatic code review bot has recently found that my fat fingers struck again and I accidentally switched to using wrong limit variable in the `GetLatest` method. It should matter in approximately zero percent of cases, since Bigscreen sets the limit variable properly and everything else worked fine anyway, so if you're already using the previous 4.0.0.0, no need to update. But if you aren't, [here's an updated build on GitHub actions](https://github.com/Nullcaller/jellyfin-plugin-dlna/actions/runs/11564162008) where it's fixed and the [build-artifact.zip](https://github.com/user-attachments/files/17549743/build-artifact.zip) for anyone reading this after GitHub scrubs it from Actions.

**Comment by crobibero** [comment]
I haven't had time to properly review the changes so it wasn't included in v4. There is no scheduled release cadence for plugins, only free time restrictions. I should be able to get enough time for a review before the end of the week.
