### ISSUE TITLE
Error in log with 10.10.0

### ISSUE THREAD

**Issue by spacemanspiff2007** [jellyfin/jellyfin-plugin-dlna#86]
Edit: This was with version `3.0.0`, I've just seen that there is a version 4 in the pipeline. I'll wait for it to be available in the catalogue and then I'll test again.

---

After updating to `10.10.0` the following error appears in the logs. SendTo still not working.

````
[2024-10-27 05:42:56.939 +01:00] [ERR] [43] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/dlna/1754574e-cafb-4a26-bd8b-6bb8f70237cf/description.xml".
System.MissingMethodException: Method not found: 'Void MediaBrowser.Model.Dlna.DeviceProfile.set_Id(System.String)'.
   at Jellyfin.Plugin.Dlna.Profiles.DefaultProfile..ctor()
   at Jellyfin.Plugin.Dlna.DlnaManager.GetServerDescriptionXml(IHeaderDictionary headers, String serverUuId, String serverAddress)
   at Jellyfin.Plugin.Dlna.Api.DlnaServerController.GetDescriptionXml(String serverId)
   at lambda_method1132(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
````

**Comment by disgustipated** [comment]
It looks like some other things got pushed last night and seems to have broke the v3 plugin, its showing as v4 but still listed as v3 and im not seeing that my server is even loading the plugin, odd.

**Comment by disgustipated** [comment]
i had to update the server to 10.10 for the plugin thats showing as v3 to work, the one in the catalog from within the server i think should actually be v4 now but it has changes in it for 10.10.

**Comment by disgustipated** [comment]
I'm not able to reproduce that after updating server to 10.10. since the plugin is still showing v3 from the catalog, but it should be v4, yours might not be updating. try uninstalling the plugin from your server and then reinstalling it from the catalog.

**Comment by crobibero** [comment]
I missed merging the PR that set the version to 4. This had been rectified and a new version released
