### ISSUE TITLE
DLNA not showing certain folders' content

### ISSUE THREAD

**Issue by ptasznikarium** [jellyfin/jellyfin-plugin-dlna#9]
When using DLNA, going to 'Folders' view, then my music folder, then Artist folder, you should see Albums' folders of that Artist.
Problem is if Artist's folder is in format "Artist_name -- discography", then there is no Albums listed.

Content is still available if I access it by anything else than 'Folders' view.

It was working fine before JF 10.7 (I went from 10.6.x to 10.7.1) and still is broken in 10.7.2

All Artists with folders in format "Artist_name -- discography" and "Artist_name -- discography YYYY" are affected.

I tried renaming test folder by removing " -- discography" part. refreshing metadata, and restarting JF, but in DLNA I still could see old "Artist_name -- discography" folder, so not sure how to test it....

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: None, JF is installed
 - Clients: Any DLNA client
 - Jellyfin Version: 10.7.1 and 10.7.2
 - Storage: NAS, Linux EXT

**Comment by Hadatko** [comment]
Hello. This looks still an issue :'( with 0.16.0

**Comment by mikeilabs** [comment]
> Hello. This looks still an issue :'( at least on TCL tv
> 
> I noticed a lot of errors like this:
> 
> ```
> [2023-12-14 04:02:17.935 +01:00] [ERR] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
>    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
>    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
>    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
>    at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
>    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
>    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
>    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
> [2023-12-14 04:02:17.954 +01:00] [INF] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/data/movies/Akcne/1997 - Piaty element/The.Fifth.Element.BluRay.1080p.x264.5.1.Judas.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/dbf9430e-14ce-6053-32fd-6aa460c31bcc/stream.mov?MediaSourceId=dbf9430e14ce605332fd6aa460c31bcc&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=b8381ba5293b2b9de9075d70749f7b34"
> [2023-12-14 04:02:17.954 +01:00] [INF] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/data/movies/Akcne/1998 - Armagedon/Armageddon.avi", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/7017a8cb-7ba2-28fb-ded4-943220072891/stream.mkv?MediaSourceId=7017a8cb7ba228fbded4943220072891&Static=true&VideoCodec=mpeg4&AudioCodec=mp3&AudioStreamIndex=1&api_key=<token>&Tag=fec8c7bb8c8a6e29680d354b8c38bf7f"
> [2023-12-14 04:02:17.955 +01:00] [ERR] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
>    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
>    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
>    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
>    at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
>    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
>    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
>    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
> [2023-12-14 04:02:17.971 +01:00] [INF] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/data/movies/Akcne/1997 - Piaty element/The.Fifth.Element.BluRay.1080p.x264.5.1.Judas.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/dbf9430e-14ce-6053-32fd-6aa460c31bcc/stream.mov?MediaSourceId=dbf9430e14ce605332fd6aa460c31bcc&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=b8381ba5293b2b9de9075d70749f7b34"
> [2023-12-14 04:02:17.972 +01:00] [INF] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/data/movies/Akcne/1998 - Armagedon/Armageddon.avi", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/7017a8cb-7ba2-28fb-ded4-943220072891/stream.mkv?MediaSourceId=7017a8cb7ba228fbded4943220072891&Static=true&VideoCodec=mpeg4&AudioCodec=mp3&AudioStreamIndex=1&api_key=<token>&Tag=fec8c7bb8c8a6e29680d354b8c38bf7f"
> [2023-12-14 04:02:17.972 +01:00] [ERR] [131] Emby.Dlna.ContentDirectory.ContentDirectoryService: Error processing control request
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
>    at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
>    at Emby.Dlna.Didl.DidlBuilder.AddVideoResource(XmlWriter writer, BaseItem video, String deviceId, Filter filter, StreamInfo streamInfo)
>    at Emby.Dlna.Didl.DidlBuilder.WriteItemElement(XmlWriter writer, BaseItem item, User user, BaseItem context, Nullable`1 contextStubType, String deviceId, Filter filter, StreamInfo streamInfo)
>    at Emby.Dlna.ContentDirectory.ControlHandler.HandleBrowse(XmlWriter xmlWriter, IReadOnlyDictionary`2 sparams, String deviceId)
>    at Emby.Dlna.Service.BaseControlHandler.CreateControlResponse(ControlRequestInfo requestInfo)
>    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestInternalAsync(ControlRequest request)
>    at Emby.Dlna.Service.BaseControlHandler.ProcessControlRequestAsync(ControlRequest request)
> [2023-12-14 04:02:19.908 +01:00] [INF] [144] Emby.Dlna.ContentDirectory.ContentDirectoryService: StreamBuilder.BuildVideoItem( Profile="Generic Device", Path="/data/movies/ARozpravky/1992 - Tom a Jerry - Film Cz/Tom a Jerry - Film  (1992) Cz.avi", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/c3488636-663e-f823-5743-c5487ddce522/stream.avi?MediaSourceId=c3488636663ef8235743c5487ddce522&Static=true&VideoCodec=mpeg4&AudioCodec=mp3&AudioStreamIndex=1&api_key=<token>&Tag=91339e65d8fa0950dcc2a8bd22d54492"
> ```

Have the same Issue, switched back to Emby because no directories or files are displayed in Jellyfin
